[package]
name = "krets-gui"
version = "0.1.1"
edition = "2024"

[dependencies]
arrow = "56.2.0"
eframe = "0.33.0"
egui = "0.33.0"
egui_extras = "0.33.0"
egui_plot = "0.34.0"
egui_table = "0.5.0"
parquet = { workspace = true }


[lints]
workspace = true
